name: ZxSpectrumEmulator
description: An implmentation of a ZX Spectrum Emulator.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ZxSpectrum:
    path: ../ZxSpectrum
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google.scr
    - assets/48.rom
    - assets/games/3DDeathChase.z80
    - assets/games/ADayInTheLife.z80
    - assets/games/BruceLee.z80
    - assets/games/ChuckieEgg.z80
    - assets/games/Cube.z80
    - assets/games/CyrusIsChess.z80
    - assets/games/elite.z80
    - assets/games/FullThrottle.z80
    - assets/games/galaxian.z80
    - assets/games/GreenBeret.z80
    - assets/games/GreenBeret.sna
    - assets/games/Jetpac.z80
    - assets/games/JetSetWilly.z80
    - assets/games/ManicMiner.z80
    - assets/games/pacman.z80
    - assets/games/pacman96.z80
    - assets/games/SpaceInvaders.z80
    - assets/games/StopTheExpress.z80
