name: ZxSpectrumEmulator
description: An implmentation of a ZX Spectrum Emulator.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ZxSpectrum:
    path: ../ZxSpectrum
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google.scr
    - assets/48.rom
